apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kube-prometheus
    app.kubernetes.io/part-of: kube-prometheus
    prometheus: k8s
    role: alert-rules
  name: blackbox-exporter-rules
  namespace: monitoring
spec:
  groups:
  - name: blackbox-exporter.rules
    rules:
    - alert: Baishan
      annotations:
        description: '{{ $labels.instance }}  Service unreachable'
        summary: One or more targets are unreachable.
      expr: probe_success == 0
      for: 1m
      labels:
        severity: warning
