kind: Probe
apiVersion: monitoring.coreos.com/v1
metadata:
  name: baishan-com-website
  namespace: monitoring
spec:
  interval: 60s
  module: http_2xx
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:19115
  targets:
    staticConfig:
      labels:
        env: online
      static:
        - https://www.baishan.com
